### PR TITLE
simplify ticket format validation

### PR DESCRIPTION
**Pull request by tharvik**
From the [CAS v2 documentation](https://apereo.github.io/cas/6.0.x/protocol/CAS-Protocol-V2-Specification.html#31-service-ticket), there is no need to validate the content of the ticket, the only relevant check is that it needs to begin with "ST-" (and "PT-" for the proxy tickets).

### CODE REVIEW

**Comment by dhawes** [comment]
While I do find this version of validCASTicketFormat() more readable, my concern is that some history of ticket validation is lost with these changes. The removed tests seem to serve some purpose, and I'd have to look at the commit history to determine what it is. Have you done any of that?

**Comment by pames** [comment]
As the person responsible for the bulk of the original atrocities in the code here, I feel an obligation to chime in:

The check was added because there is/was essentially no cases where a non-ASCII ticket in that form was found in any CAS server implementation, and this made reasoning about how to use any value that made it through that function elsewhere a lot simpler given that it comes from untrusted clients. That's why the tests use weird values like non-printable control characters.

This change means the return value from getCASTicket is much less "sane", usages I spot checked in cas_authenticate() that get more interesting then become the call to getResponseFromServer() and createCASCookie().

getResponseFromServer() eventually uses the 'ticket' parameter directly in several apr_sprintf() call to build a query string or SAML/XML payload, so I would suggest at least adding escaping there in some way to avoid any potential issues if you want to relax the validation this much.

HTH.

**Comment by tharvik** [comment]
> The check was added because there is/was essentially no cases where a non-ASCII ticket in that form was found in any CAS server implementation, and this made reasoning about how to use any value that made it through that function elsewhere a lot simpler given that it comes from untrusted clients. That's why the tests use weird values like non-printable control characters.

I see, that's why is was limitted to such a specific range of characters (which is not ASCII btw, only `alnum + '-' + '.'`, which is not the same set as the one generated by urlencode :P).
 
> This change means the return value from getCASTicket() is much less "sane", usages I spot checked in cas_authenticate() that get more interesting then become the call to getResponseFromServer() and createCASCookie().
> getResponseFromServer() eventually uses the 'ticket' parameter directly in several apr_sprintf() call to build a query string or SAML/XML payload, so I would suggest at least adding escaping there in some way to avoid any potential issues if you want to relax the validation this much.

I've fixed `getResponseFromServer` to escape the ticket. I don't see any other problematic use but please do recheck.

**Comment by dhawes** [comment]
Thanks for the history @pames.

I'll review the new changes with that in mind.

**Pull request closed without merging**
